### ISSUE TITLE
Deduplication and outbox is executed for non-business (e.g. subscription) messages resulting in NullReferenceException being thrown because of the lack of PartitionKey

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Persistence.CosmosDB#186]
Describe the bug here by adding any information that you may know under the respective headers below.

### Observed behavior

Deduplication and outbox is executed for non-business (e.g. subscription) messages resulting in `NullReferenceException` being thrown because of the lack of PartitionKey

### Expected behavior

Messages which don't have associated partition key are skipped in the outbox mechanism.

### Symptoms

Subscription messages are sent to the error queue and endpoints can't perform pub/sub on transports that rely on message-driven pub/sub

### Steps to reproduce

Run pub/sub with non-native pub/sub transport such as ASQ

### Is it a regression?

No

### Who's affected

All customers who wish to use the CosmosDB persistence with ASQ transport

### Known Workaround

Have a behavior in the `ITransportReceive` context that set's some default partition key to be used for non-business messages and another behavior later that sets the correct partition key for business messages.

### Triage

Use the following checklist to help triage the bug by assigning the points corresponding to any applicable factors. A staff member from Particular Software will review and adjust if necessary.

| Effect | Points | Notes |
| --- | --- | --- |
| Performance degrades over time requiring manual interventions or automating restarts (1 point) | | |
| The cost of utilizing the Preview significantly exceeds what is justified (2 points) | | |
| The user interface responsiveness is longer than 10s between user request and UI response (1 point) | | |
| The issue impacts the correctness of the system but does not cause irreversible damage (3 points) | 3 | |
| The issue causes unscheduled or unplanned process shutdown. (3 points) | | |
| The issue impacts the system correctness causing irreversible damage (5 points) | | |
| The issue occurs in less than 1 in 1000 usages/invokations (0 points) | | |
| The issue occurs in greater than 1 in 1000 usages/invokations (1 point) | | |
| The issue occurs in greater than 1 in 100 usages/invokations (2 points) |2 | |
| The issue significantly impacts the adoption of the Preview for the core use-case (3 points) |3 | |

**Comment by SeanFeldman** [comment]
Also, it could be relevant to the messages marked as control messages with the `Headers.ControlMessageHeader` header.

**Comment by DavidBoike** [comment]
This specific case seems to be driven by Subscribe/Unsubscribe messages. However, Cosmos Persistence was created explicitly not supporting storage of subscriptions. It's meant to be used with transports that provide native pub/sub capabilities. MSMQ would be one but it doesn't make a lot of sense to use a cloud database with an on-premises-only message transport. The documented example is Azure Queues but [that transport also supports native pub/sub in the newest version](https://docs.particular.net/transports/azure-storage-queues/native-publish-subscribe?version=asqn_11).

Besides subscribe/unsubscribe messages, and Distributor control messages (which wouldn't apply) the only other type of control messages I can think of are the type you get when you do Reply<int> or Reply<Enum>, and I believe the acceptance tests would highlight if those didn't work correctly.

**Comment by DavidBoike** [comment]
The fundamental issue here is that Cosmos DB persistence is not designed to work with message-driven publish/subscribe - if it had, it would have implemented subscription persistence. So you can only get this bug by combining Cosmos DB persistence with a transport that still uses message-driven subscriptions + another persistence (like Azure Table Storage) for subscriptions.

For the forthcoming 1.0 release, we have fixed this by throwing an exception on startup if the endpoint has message-driven subscriptions activated.

After that, the next major version will target NServiceBus 8, where message-driven publish/subscribe is no longer a thing.
