### ISSUE TITLE
Implement pessimistic locking

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Persistence.CosmosDB#24]
CosmosDB has no pessimistic locking built-in. To support this mode, which would have a performance impact, we can implement a strategy similar to [RavenDB saga persistence](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/SagaPersister/SagaDataLease.cs) for Cosmos DB saga records as an opt-in option.

**Comment by danielmarbach** [comment]
Some additional reading 

- [Partial document updates](https://docs.microsoft.com/en-us/azure/cosmos-db/partial-document-update-getting-started)
- [Working with datetime](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/working-with-dates)

**Comment by boblangley** [comment]
We merged [the PR](https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/281) that implements pessimistic locking support and will release it as part of the upcoming 1.1.0 release.
