### ISSUE TITLE
Could not enumerate all types for 'NServiceBus.Persistence.CosmosDB'

### ISSUE THREAD

**Issue by kylejuliandev** [Particular/NServiceBus.Persistence.CosmosDB#294]
Hi,

I have been having some issues during a recent upgrade/migration to .NET 6.0, following on from this [announcement](https://discuss.particular.net/t/nservicebus-support-for-net-6-complete/2902). I originally raised my issue on the [Core repository](https://github.com/Particular/NServiceBus/issues/6226). This issue details the exception and stack trace that I got after upgrading to `NServiceBus.Persistence.CosmosDB` 1.0.0. This package does not play nicely when I introduce another reference to `Microsoft.Azure.Cosmos`, specifically any reference to a version > 3.20.1.

**Comment by kylejuliandev** [comment]
I have created a sample project which replicates this issue. You can find it [here](https://github.com/kylejuliandev/NServiceBusPersistenceCosmosIssue).

The repository it is configured to using the LearningTransport and does not explicitly apply the CosmosDB saga persistence in code.

**Comment by danielmarbach** [comment]
@kylejuliandev We are in the process of releasing a new minor version of the persistence that will bring support for the new Microsoft.Azure.Cosmos updates. We are wrapping up things, hopefully at the end of this week. I can ping you again on this issue once we have released it with the necessary pointers.

**Comment by danielmarbach** [comment]
@kylejuliandev We have released 1.1.0 that supports the new 3.23 version of the client. For more details about the release see

https://discuss.particular.net/t/nservicebus-persistence-cosmosdb-1-1-0-minor-release-available/2908

as well as our upgrade guide

https://docs.particular.net/persistence/upgrades/cosmosdb-1to1.1

We have also added comprehensive documentation about the new more convenient transaction API that we introduced in this release

https://docs.particular.net/persistence/cosmosdb/transactions
