### ISSUE TITLE
Provide a little more info around what happens with high contention creating a saga

### ISSUE THREAD

**Issue by bbrandt** [Particular/NServiceBus.Persistence.CosmosDB#655]
#### Is your improvement related to a problem? Please describe.
Not a problem really, just an easily misunderstood behavior of ComsosDB Saga persistence.  What happens when many similar events come close together that map to the same id for the saga?

#### Describe the suggested solution
Make the expectations for this behavior more clear so devs can know that it is important to avoid it.  Could you run the tests for this PR so that I can link to the results in some internal docs for my team?  After the tests are run, I am fine with closing the PR without merging.
https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/653
        
#### Describe alternatives you've considered
SQL Persistence handles this better?

**Comment by TravisNickels** [comment]
Thank you for highlighting this and sharing additional details about the observed behavior. We've made updates to our documentation for [starting a saga](https://docs.particular.net/nservicebus/sagas/concurrency#starting-a-saga) to help with the clarity.  If you have any further questions or if there's anything else you'd like to discuss, please feel free to let us know.
