### ISSUE TITLE
Add built-in support for configuring partition key extraction rules

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Persistence.CosmosDB#69]
Raised by @ivan-l

We found that teams who used our persistence package had a difficult time wrapping their heads around the fact that one needs to look inside a message in order to determine the partition to which a Cosmos session needs to be scoped. We thought of but never got around to it, to implement a fluent API for configuring message partition key extraction rules to make that configuration easier and clearer to reason about. For example, we considered the following:

```
endpointConfiguration.UsePersistence<CosmosDbPersistence>()
    .CosmosClient(new CosmosClient("ConnectionString"))
    .DatabaseName("DatabaseName")
    .ForMessage<OneSpecificMessage>(message => (new ContainerInformation("containerName", "partitionKeyPath"), message.PartitionKeyValue))
    .ForMessage<ISomeMessageInterface>(message => (new ContainerInformation("containerName", "partitionKeyPath"), message.PartitionKeyValue))
```

**Comment by danielmarbach** [comment]
Additionally, a physical mapping function could also be added, ideas

```
endpointConfiguration.UsePersistence<CosmosDbPersistence>()
    .CosmosClient(new CosmosClient("ConnectionString"))
    .DatabaseName("DatabaseName")
    .ForMessageWithHeaders<OneSpecificMessage>(headers => (new ContainerInformation("containerName", "partitionKeyPath"), headers["CustomPartitionKeyHeader")) // used to derive the enclosed message type
    .ForHeader(headers=> (new ContainerInformation("containerName", "partitionKeyPath"), headers["CustomPartitionKeyHeader"))) // kind of catch all
```

**Comment by danielmarbach** [comment]
A bit of context

We actually had helper methods like this at one point but we decided to not add them out of the box and first get a better understanding of what customers do with the flexibility the persister provides before we go down the path of building convenience APIs

**Comment by boblangley** [comment]
We started [a PR](https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/282) for this and will release it as a new minor shortly.

**Comment by danielmarbach** [comment]
@Ivan-L We have released 1.1.0. For more details about the release see

https://discuss.particular.net/t/nservicebus-persistence-cosmosdb-1-1-0-minor-release-available/2908

as well as our upgrade guide

https://docs.particular.net/persistence/upgrades/cosmosdb-1to1.1

We have also added comprehensive documentation about the new more convenient transaction API that we introduced in this release

https://docs.particular.net/persistence/cosmosdb/transactions

**Comment by Ivan-L** [comment]
Hi @danielmarbach this is really great, thank you! We have a few projects that we can migrate to use this fluent API.

**Comment by danielmarbach** [comment]
@Ivan-L cool! Let us know if you discover loopholes or inconvenient stuff, in case you find any so that we can further improve things in next enhancement releases.
