### ISSUE TITLE
Multiple Endpoints Setup Exception thrown

### ISSUE THREAD

**Issue by AlexandruPopa-CAL** [Particular/NServiceBus.Persistence.CosmosDB#76]
Hi guys,
I am getting this exception on multiple endpoints setup, is this feature not supported or I'm doing something wrong 🤔
![image](https://user-images.githubusercontent.com/71499781/95959607-9b18a200-0dfa-11eb-923d-e57911c2d949.png)

**Comment by andreasohlund** [comment]
Can you share the code for the setup? 

Note that you need to have separate container instances for each endpoint instance.

See https://docs.particular.net/samples/hosting/generic-multi-hosting/ for more details

**Comment by AlexandruPopa-CAL** [comment]
Hi Andreas,
Thanks for your reply.

Yes, we use separate containers.

The problem is we use EndpointConfiguration.UsePersistence<CosmosPersistence>(); only for one endpoint, strangely the CosmosPersistance class is called for all the other endpoints as well.

Unfortunately can't share the code but will try to create a code sample replicating the issue.

**Comment by AlexandruPopa-CAL** [comment]
Please find attached a screenshot and a code sample.

![image](https://user-images.githubusercontent.com/71499781/95972174-09b12c00-0e0a-11eb-874b-8f040ce13288.png)

`
using System;
using System.Threading.Tasks;
using Microsoft.Azure.Cosmos;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using NServiceBus;
using NServiceBus.Features;

namespace NServiceBusCosmosMultipleEndpoints
{
    public class Program
    {
        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        public static Task Main(string[] args)
        {
            var endpointOneBuilder = ConfigureEndpointWithCosmosDB(CreateHostBuilder(args)).Build();
            var endpointTwoBuilder = ConfigureEndpointWithoutCosmosDB(CreateHostBuilder(args)).Build();

            return Task.WhenAll(endpointOneBuilder.RunAsync(), endpointTwoBuilder.RunAsync());
        }

        private static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((ctx, container) =>
                {
                    Console.Title = "Multiple endpoints Test";

                });

        private static IHostBuilder ConfigureEndpointWithCosmosDB(IHostBuilder builder)
        {
            builder.UseNServiceBus(ctx =>
            {
                var endpointConfiguration = new EndpointConfiguration("Sales");

                _ = endpointConfiguration.UseTransport<LearningTransport>();
                var persistence = endpointConfiguration.UsePersistence<CosmosPersistence>();
                var connection = @"AccountEndpoint = https://localhost:8084/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
                var cosmosClient = new CosmosClient(connection);
                persistence.CosmosClient(cosmosClient);

                return endpointConfiguration;
            });

            return builder;
        }

        private static IHostBuilder ConfigureEndpointWithoutCosmosDB(IHostBuilder builder)
        {
            builder.UseNServiceBus(ctx =>
            {
                var endpointConfiguration = new EndpointConfiguration("Ops");

                _ = endpointConfiguration.UseTransport<LearningTransport>();
                endpointConfiguration.DisableFeature<Sagas>();
                _ = endpointConfiguration.UseSerialization<NewtonsoftSerializer>();
                endpointConfiguration.SendOnly();
                endpointConfiguration.LimitMessageProcessingConcurrencyTo(1);

                return endpointConfiguration;
            });

            return builder;
        }
    }
}
`
`
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="NServiceBus" Version="7.4.3" />
    <PackageReference Include="NServiceBus.Extensions.Hosting" Version="1.1.0" />
    <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="2.2.0" />
    <PackageReference Include="NServiceBus.Persistence.CosmosDB" Version="0.1.0" />
    <PackageReference Include="NServiceBus.Serilog" Version="7.2.0" />
    <PackageReference Include="NServiceBus.Extensions.DependencyInjection" Version="1.0.1" />

  </ItemGroup>

</Project>
`

**Comment by andreasohlund** [comment]
Since the installers are found via assembly scanning you need to make sure that you exclude all the types from NServiceBus.Persistence.CosmosDB in the endpoint that isn't using it.

See https://docs.particular.net/nservicebus/hosting/assembly-scanning#exclude-a-list-approach

Does that make sense?

**Comment by AlexandruPopa-CAL** [comment]
Thanks, that did the job.
