### ISSUE TITLE
Unable to retrieve the container name exception thrown for empty handlers

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Persistence.CosmosDB#86]
## Who's affected

- All customers using the persistence

## Symptoms

For cases when a message is destined to go to a handler that doesn't use CosmosDB a synchronized storage session is still created behind the scenes. In such cases it is not necessary to provide the container information yet is is enforced by us and an exception is thrown

> Unable to retrieve the container name and the partition key during processing. Make sure that either `persistence.Container()` is used or the relevant container information is available on the message handling pipeline.

**Comment by boblangley** [comment]
We triaged this issue as critical and will release a patch release as soon as possible.

**Comment by boblangley** [comment]
The package has been pushed to NuGet. Writing the discourse announcement now.
